language: cpp

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libcurl4-openssl-dev libjsoncpp-dev libargtable2-dev libboost-test-dev libgnutls-dev libgcrypt11-dev dpkg-dev devscripts valgrind
 - sudo apt-get source libmicrohttpd
 - cd libmicrohttpd-0.4.6
 - debuild -us -uc
 - sudo dpkg -i ../libmicrohttpd5_0.4.6-1_amd64.deb ../libmicrohttpd-dev_0.4.6-1_amd64.deb
 - sudo pip install cpp-coveralls


env:
 - HTTP_SERVER=YES HTTP_CLIENT=YES COMPILE_STUBGEN=YES
 - HTTP_SERVER=NO HTTP_CLIENT=NO COMPILE_STUBGEN=NO


compiler:
  - clang
  - gcc

script: 
    - mkdir -p build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DHTTP_CLIENT=${HTTP_CLIENT} -DHTTP_SERVER=${HTTP_SERVER} -DCOMPILE_STUBGEN=${COMPILE_STUBGEN} .. 
    - make
    - valgrind --leak-check=full --error-exitcode=1 ./bin/unit_testsuite
    - make test
    - sudo make install && sudo ldconfig
    - g++ ../src/examples/simpleclient.cpp -ljsonrpccpp-client -ljsoncpp -ljsonrpccpp-common -lcurl -o sampleclient
    - g++ ../src/examples/simpleserver.cpp -ljsonrpccpp-server -ljsoncpp -ljsonrpccpp-common -lmicrohttpd -o sampleserver
    - sudo make uninstall
after_success:
    - cd ..
    - coveralls -e src/test -e src/examples -e cmake -e /usr/include -e build/CMakeFiles -E '.*\.h'
